EMAIL_ADDRESS = "studentfeedbacks44@gmail.com"
EMAIL_PASSWORD = "uxkbcrgwsbsxjjrh"

DB_HOST = "showandtell-db.cd48qeascwz8.us-east-2.rds.amazonaws.com"
DB_PORT = "3306"
DB_NAME = "Showtell"
DB_USER = "admin"
DB_PASSWORD = "turtleFan336#"

ADMIN_KEY = "super-secret-string"
CURRENT_WEEK = 6
